# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [ 'tar.gz' ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

brews:
  - name: git-overlay
    homepage: "https://github.com/rjocoleman/git-overlay"
    description: "Git overlay tool for managing upstream repositories"
    repository:
      owner: rjocoleman
      name: git-overlay
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    install: |
      bin.install "git-overlay"
    test: |
      system "#{bin}/git-overlay", "--version"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - '^style:'
      - '^refactor:'
