# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitOverlay < Formula
  desc "Git overlay tool for managing upstream repositories"
  homepage "https://github.com/rjocoleman/git-overlay"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rjocoleman/git-overlay/releases/download/v0.2.1/git-overlay_ darwin_x86_64.tar.gz"
      sha256 "517e0ff3cff8aef3f4829c57467d7495b61e6a89055f24e6123573edc699c933"

      def install
        bin.install "git-overlay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rjocoleman/git-overlay/releases/download/v0.2.1/git-overlay_ darwin_arm64.tar.gz"
      sha256 "671bc86410ba86311422a067071d045fddb988ede6bc9ca499bf8d6d328d0b68"

      def install
        bin.install "git-overlay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjocoleman/git-overlay/releases/download/v0.2.1/git-overlay_ linux_x86_64.tar.gz"
        sha256 "7f1dd0b6e334e02a2880a1fa9b554d2ba4fc6bf4d35119bad36fd46a8ffb4807"

        def install
          bin.install "git-overlay"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rjocoleman/git-overlay/releases/download/v0.2.1/git-overlay_ linux_arm64.tar.gz"
        sha256 "965b3837891131d1fddd4e9dc611490ef0d78e15e32d2aa8b0cdf1453dc6f591"

        def install
          bin.install "git-overlay"
        end
      end
    end
  end

  test do
    system "#{bin}/git-overlay", "--version"
  end
end
